### ISSUE TITLE
script return ERROR: cvdinfo: Verification: Can't verify database integrity

### ISSUE THREAD

**Issue by hdep** [vrtadmin/clamav-faq#31]
Hello,

I am using this script in order to create a local repo for my servers.
from time to time the script is reporting errors, here is the output : 

TXT from DNS: 0.98.7:55:21075:1448027370:1:63:44070:270
FIELDS main=55 daily=21075 bytecode=270
main old: 55 current: 55
daily old: 21074 current: 21075
Â«Â daily.cvdÂ Â» -> Â«Â temp/daily.cvdÂ Â»
ERROR: cvdinfo: Verification: Can't verify database integrity
2015-11-20 15:23:59 URL:http://database.clamav.net/daily.cvd [41495027/41495027] -> "daily.cvd" [1]
file temp/daily.cvd not touched by wget
Â«Â temp/daily.cvdÂ Â» supprimÃ©
bytecode old: 270 current: 270

 I don't know what happen when this message shows up.
Do you have any advice for troubleshooting this ? 

Best regards,

**Comment by finchy** [comment]
Dear hdep,

A more appropriate place to get your question answered would be the ClamAV users list:

http://lists.clamav.net/mailman/listinfo/clamav-users

While I try, I can't get to everyone's email personally and this allows us to leverage everyone on the team as well as the whole open source community.

Thank you.
