### ISSUE TITLE
[FAQ - Installation] Include references to SlackBuilds.org

### ISSUE THREAD

**Issue by GreenLunar** [vrtadmin/clamav-faq#33]
See http://slackbuilds.org/result/?search=clamav

There are various of Slackware package manager that handle automatic installation of SBo packages.

[Sport](http://slackermedia.info/sport/) `sport install clamav`
[Slpkg](https://github.com/dslackw/slpkg)
[slapt-src](http://software.jaos.org/#slapt-src) `slapt-src -i clamav`
[sbotools](http://dawnrazor.net/sbotools/)
[Sbopkg](http://www.sbopkg.org/) `sbopkg -i clamav`
and many others...

**Comment by finchy** [comment]
Please open a pull request against the document to be modified, and I'll review.

**Comment by GreenLunar** [comment]
Where is the file that needs to be edited?
