### ISSUE TITLE
Source files of clamdoc.pdf

### ISSUE THREAD

**Issue by GreenLunar** [vrtadmin/clamav-faq#34]
Where are the source files of file clamdoc.pdf?

**Comment by sage-oli-wood** [comment]
I was just about to add the same things.  It would be great to have the source files generate both an online HTML version on the site and the downloadable PDF.

**Comment by GreenLunar** [comment]
I would love to have it available as ePUB too.

**Comment by finchy** [comment]
The .tex file is in the docs directory inside the tarball.  We make the PDF available online.

**Comment by GreenLunar** [comment]
>The .tex file is in the docs directory inside the tarball.

I did not find it.
