### ISSUE TITLE
Private Local Mirror FAQ misleading

### ISSUE THREAD

**Issue by kiplandiles** [vrtadmin/clamav-faq#36]
**2. Serve CVD files from a local web server.**
This section is misleading and actually does not work with the latest release of freshclam. The new configuration directive is **PrivateMirror**. Changing **DatabaseMirror** to point to the local private mirror will connect but will not be successful downloading the database files.

**Comment by finchy** [comment]
If you'd like to fix this by submitting a pull request, that's the best way to contribute.
