### ISSUE TITLE
document memory/disk usage when large (1 GB) file is streamed in 1MB chunks into clamd

### ISSUE THREAD

**Issue by ralfhauser** [vrtadmin/clamav-faq#39]
Will the chunks be assembled to the GB-file in a temp directory or can the "signatures" be calculated incrementally and the processed chunks are deallocated?

When reading the man page on the /etc/clamav/clamd.conf arguments such as
MaxScanSize 100M
MaxFileSize 25M
MaxRecursion 10
MaxFiles 10000
MaxPartitions 50
MaxIconsPE 100
StreamMaxLength 25M
LogFileMaxSize 0
OnAccessMaxFileSize 5M

it appears that resource consumption is proportional to the size of item to scan.

Or could clam offer an operations mode where most (not necessary all) protection is still around when only working sequentially on chunks?

see also http://www.gossamer-threads.com/lists/clamav/users/48006

**Comment by finchy** [comment]
Is this a piece of documentation you'd like to add to the FAQ?  Or should your question be on the clamav-users list?

**Comment by ralfhauser** [comment]
probably both  ;)

**Comment by vrtadmin** [comment]
If you'd like to add it to the FAQ, Please add via a pull request?
