### ISSUE TITLE
Update ClamAv in windows

### ISSUE THREAD

**Issue by MaitriSejpal** [vrtadmin/clamav-faq#47]
I have ClamAv is on my VM(Virtual Machine).

In My live site(Made in MVC Framewrok) , to scan Cv i am using ClamAv. now i want to upgrade ClamAv. 

but i am not understanding by, it is to simply update the nclam Nudget Package or anything else?

and if i update that will it be effect on live site?

**Comment by finchy** [comment]
Please direct your questions to the mailing list.  http://lists.clamav.net/cgi-bin/mailman/listinfo/clamav-users 

The community monitors the mailing lists, not the faq GitHub,
